#!/bin/sh
#
# chkconfig: 35 90 12
# description: Foo server
#

NAME="AESDsocket"
AESDEXEC=/usr/bin/aesdsocket
AESDARGS="-d"

### main logic ###
case "$1" in
  start)
        echo "Starting $NAME "
        start-stop-daemon -S -b -x $AESDEXEC -a $AESDARGS
        RETCODE=$?
        echo $RETCODE
        ;;
  stop)
        echo "Stopping" "$NAME"
        start-stop-daemon -K -x $AESDEXEC -s SIGTERM
        RETVAL=$?
        echo $RETVAL
        ;;
  status)
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0