#!/bin/sh
#
# chkconfig: 35 90 12
# description: Foo server
#

PIDFILE=/var/run/aesdsocket.pid
NAME="AESDsocket"
AESDEXEC=/usr/bin/aesdsocket
AESDARGS="-d"

### main logic ###
case "$1" in
  start)
        log_daemon_msg "Starting $NAME "
        start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile \
                --remove-pidfile -- $AESDEXEC $AESDARGS
        RETCODE=$?
        log_end_msg $RETCODE
        ;;
  stop)
        log_daemon_msg "Stopping" "$NAME"
        start-stop-daemon --stop --pidfile $PIDFILE $AESDEXEC >/dev/null
        RETVAL=$?
        [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
        log_end_msg $RETVAL
        ;;
  status)
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0